"""initial schema

Revision ID: 33604bdea89d
Revises:
Create Date: 2026-09-17 15:01:10.029517
"""
from pathlib import Path

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '33604bdea89d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Extensions required before any geometry column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # Vietnamese-insensitive normalisation used for search columns.
    op.execute(Path(__file__).resolve().parents[2].joinpath(
        "functions", "vn_normalize.sql").read_text(encoding="utf-8"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('official_code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_version', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['administrative_units.id'], name=op.f('fk_administrative_units_parent_id_administrative_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrative_units'))
    )
    op.create_index('ix_admin_units_code_valid', 'administrative_units', ['official_code', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_admin_units_name', 'administrative_units', ['normalized_name'], unique=False)
    op.create_table('authorities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('authority_type', sa.String(length=64), nullable=False),
    sa.Column('jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('official_domain', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authorities'))
    )
    op.create_index(op.f('ix_authorities_jurisdiction'), 'authorities', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_authorities_normalized_name'), 'authorities', ['normalized_name'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_tasks'))
    )
    op.create_index('ix_review_target', 'review_tasks', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_table('coverage_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_unit_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('dataset_count', sa.Integer(), nullable=False),
    sa.Column('reviewed_count', sa.Integer(), nullable=False),
    sa.Column('last_checked', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_unit_id'], ['administrative_units.id'], name=op.f('fk_coverage_summaries_admin_unit_id_administrative_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverage_summaries'))
    )
    op.create_index(op.f('ix_coverage_summaries_admin_unit_id'), 'coverage_summaries', ['admin_unit_id'], unique=False)
    op.create_table('planning_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('official_information_code', sa.String(length=128), nullable=True),
    sa.Column('official_file_code', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('planning_type', sa.String(length=128), nullable=True),
    sa.Column('scale', sa.String(length=64), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('approving_authority', sa.String(length=512), nullable=True),
    sa.Column('consultant', sa.String(length=512), nullable=True),
    sa.Column('investor', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('admin_unit_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_unit_id'], ['administrative_units.id'], name=op.f('fk_planning_records_admin_unit_id_administrative_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_records'))
    )
    op.create_index(op.f('ix_planning_records_jurisdiction'), 'planning_records', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_planning_records_normalized_title'), 'planning_records', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_planning_records_official_file_code'), 'planning_records', ['official_file_code'], unique=False)
    op.create_index(op.f('ix_planning_records_official_information_code'), 'planning_records', ['official_information_code'], unique=False)
    op.create_index(op.f('ix_planning_records_planning_type'), 'planning_records', ['planning_type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('authority_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('terms_url', sa.Text(), nullable=True),
    sa.Column('rights_statement', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('redistribution_status', sa.String(length=64), nullable=False),
    sa.Column('crawl_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('descriptor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], name=op.f('fk_sources_authority_id_authorities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('source_key', name=op.f('uq_sources_source_key'))
    )
    op.create_index(op.f('ix_sources_jurisdiction'), 'sources', ['jurisdiction'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('software_commit', sa.String(length=64), nullable=True),
    sa.Column('configuration_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('discovered_count', sa.Integer(), nullable=False),
    sa.Column('downloaded_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ingestion_runs_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('source_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('retrieved_url', sa.Text(), nullable=True),
    sa.Column('retrieval_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('object_storage_key', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('detected_format', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_artifacts_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_artifacts'))
    )
    op.create_index(op.f('ix_source_artifacts_content_sha256'), 'source_artifacts', ['content_sha256'], unique=False)
    op.create_index('ix_source_artifacts_source_sha', 'source_artifacts', ['source_id', 'content_sha256'], unique=False)
    op.create_index('ix_source_artifacts_url', 'source_artifacts', ['canonical_url'], unique=False)
    op.create_table('planning_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('planning_record_id', sa.Uuid(), nullable=False),
    sa.Column('version_kind', sa.String(length=64), nullable=False),
    sa.Column('version_label', sa.String(length=128), nullable=True),
    sa.Column('approval_decision_number', sa.String(length=128), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('legal_status', sa.String(length=64), nullable=False),
    sa.Column('supersedes_version_id', sa.Uuid(), nullable=True),
    sa.Column('source_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planning_record_id'], ['planning_records.id'], name=op.f('fk_planning_versions_planning_record_id_planning_records')),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['source_artifacts.id'], name=op.f('fk_planning_versions_source_artifact_id_source_artifacts')),
    sa.ForeignKeyConstraint(['supersedes_version_id'], ['planning_versions.id'], name=op.f('fk_planning_versions_supersedes_version_id_planning_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_versions'))
    )
    op.create_index(op.f('ix_planning_versions_approval_decision_number'), 'planning_versions', ['approval_decision_number'], unique=False)
    op.create_index(op.f('ix_planning_versions_effective_from'), 'planning_versions', ['effective_from'], unique=False)
    op.create_index(op.f('ix_planning_versions_planning_record_id'), 'planning_versions', ['planning_record_id'], unique=False)
    op.create_index('ix_planning_versions_record_effective', 'planning_versions', ['planning_record_id', 'effective_from'], unique=False)
    op.create_table('provenance_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('input_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=True),
    sa.Column('tool_version', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('fk_provenance_events_run_id_ingestion_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provenance_events'))
    )
    op.create_index(op.f('ix_provenance_events_created_at'), 'provenance_events', ['created_at'], unique=False)
    op.create_index('ix_provenance_run', 'provenance_events', ['run_id'], unique=False)
    op.create_index('ix_provenance_target', 'provenance_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('quality_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('fk_quality_observations_run_id_ingestion_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_observations'))
    )
    op.create_index('ix_quality_open', 'quality_observations', ['resolved_at'], unique=False)
    op.create_index('ix_quality_rule', 'quality_observations', ['rule_code'], unique=False)
    op.create_index('ix_quality_target', 'quality_observations', ['target_type', 'target_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('planning_version_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_group', sa.String(length=64), nullable=False),
    sa.Column('dataset_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('original_format', sa.String(length=64), nullable=True),
    sa.Column('original_crs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canonical_crs', sa.Integer(), nullable=False),
    sa.Column('derivation_level', sa.String(length=64), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('quality_state', sa.String(length=32), nullable=False),
    sa.Column('source_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planning_version_id'], ['planning_versions.id'], name=op.f('fk_datasets_planning_version_id_planning_versions')),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['source_artifacts.id'], name=op.f('fk_datasets_source_artifact_id_source_artifacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index(op.f('ix_datasets_dataset_group'), 'datasets', ['dataset_group'], unique=False)
    op.create_index(op.f('ix_datasets_derivation_level'), 'datasets', ['derivation_level'], unique=False)
    op.create_index(op.f('ix_datasets_planning_version_id'), 'datasets', ['planning_version_id'], unique=False)
    op.create_index(op.f('ix_datasets_review_status'), 'datasets', ['review_status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('planning_version_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('document_number', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('normalized_title', sa.Text(), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.String(length=512), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['source_artifacts.id'], name=op.f('fk_documents_artifact_id_source_artifacts')),
    sa.ForeignKeyConstraint(['planning_version_id'], ['planning_versions.id'], name=op.f('fk_documents_planning_version_id_planning_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_document_number'), 'documents', ['document_number'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_normalized_title'), 'documents', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_documents_planning_version_id'), 'documents', ['planning_version_id'], unique=False)
    op.create_table('georeference_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('transform_type', sa.String(length=32), nullable=False),
    sa.Column('target_srid', sa.Integer(), nullable=False),
    sa.Column('gcps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('residuals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transform_coefficients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_storage_key', sa.Text(), nullable=True),
    sa.Column('output_sha256', sa.String(length=64), nullable=True),
    sa.Column('algorithm', sa.String(length=128), nullable=True),
    sa.Column('suggestion_source', sa.String(length=64), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_georeference_jobs_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('fk_georeference_jobs_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['source_artifacts.id'], name=op.f('fk_georeference_jobs_source_artifact_id_source_artifacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_georeference_jobs'))
    )
    op.create_index(op.f('ix_georeference_jobs_review_status'), 'georeference_jobs', ['review_status'], unique=False)
    op.create_table('layers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('thematic_group', sa.String(length=128), nullable=True),
    sa.Column('geometry_type', sa.String(length=64), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('styling_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_layers_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_layers'))
    )
    op.create_index(op.f('ix_layers_canonical_name'), 'layers', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_layers_dataset_id'), 'layers', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_layers_thematic_group'), 'layers', ['thematic_group'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('planning_version_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('artifact_key', sa.Text(), nullable=True),
    sa.Column('manifest_key', sa.Text(), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('feature_count', sa.BigInteger(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_zoom', sa.Integer(), nullable=True),
    sa.Column('max_zoom', sa.Integer(), nullable=True),
    sa.Column('software_commit', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_publications_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['planning_version_id'], ['planning_versions.id'], name=op.f('fk_publications_planning_version_id_planning_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications'))
    )
    op.create_index(op.f('ix_publications_checksum_sha256'), 'publications', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_publications_planning_version_id'), 'publications', ['planning_version_id'], unique=False)
    op.create_table('change_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_layer_id', sa.Uuid(), nullable=False),
    sa.Column('to_layer_id', sa.Uuid(), nullable=False),
    sa.Column('algorithm', sa.String(length=128), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_layer_id'], ['layers.id'], name=op.f('fk_change_sets_from_layer_id_layers')),
    sa.ForeignKeyConstraint(['to_layer_id'], ['layers.id'], name=op.f('fk_change_sets_to_layer_id_layers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_sets'))
    )
    op.create_index('ix_changeset_pair', 'change_sets', ['from_layer_id', 'to_layer_id'], unique=True)
    op.create_table('features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('layer_id', sa.Uuid(), nullable=False),
    sa.Column('stable_external_id', sa.String(length=255), nullable=True),
    sa.Column('source_object_code', sa.String(length=255), nullable=True),
    sa.Column('source_object_name', sa.String(length=512), nullable=True),
    sa.Column('normalized_name', sa.String(length=512), nullable=True),
    sa.Column('classification', sa.String(length=255), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_geometry_ewkb', sa.LargeBinary(), nullable=True),
    sa.Column('source_srid', sa.Integer(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('lineage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], name=op.f('fk_features_layer_id_layers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features'))
    )
    op.create_index('ix_features_class', 'features', ['classification'], unique=False)
    op.create_index('ix_features_layer_code', 'features', ['layer_id', 'source_object_code'], unique=False)
    op.create_index(op.f('ix_features_layer_id'), 'features', ['layer_id'], unique=False)
    op.create_index(op.f('ix_features_normalized_name'), 'features', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_features_stable_external_id'), 'features', ['stable_external_id'], unique=False)
    op.create_index('ix_features_valid', 'features', ['valid_from', 'valid_to'], unique=False)
    op.create_table('change_set_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('change_set_id', sa.Uuid(), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('from_feature_id', sa.Uuid(), nullable=True),
    sa.Column('to_feature_id', sa.Uuid(), nullable=True),
    sa.Column('match_key', sa.String(length=255), nullable=True),
    sa.Column('delta_area_m2', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_set_id'], ['change_sets.id'], name=op.f('fk_change_set_entries_change_set_id_change_sets')),
    sa.ForeignKeyConstraint(['from_feature_id'], ['features.id'], name=op.f('fk_change_set_entries_from_feature_id_features')),
    sa.ForeignKeyConstraint(['to_feature_id'], ['features.id'], name=op.f('fk_change_set_entries_to_feature_id_features')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_set_entries'))
    )
    op.create_index('ix_changeset_entries_set', 'change_set_entries', ['change_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_changeset_entries_set', table_name='change_set_entries')
    op.drop_table('change_set_entries')
    op.drop_index('ix_features_valid', table_name='features')
    op.drop_index(op.f('ix_features_stable_external_id'), table_name='features')
    op.drop_index(op.f('ix_features_normalized_name'), table_name='features')
    op.drop_index(op.f('ix_features_layer_id'), table_name='features')
    op.drop_index('ix_features_layer_code', table_name='features')
    op.drop_index('ix_features_class', table_name='features')
    op.drop_table('features')
    op.drop_index('ix_changeset_pair', table_name='change_sets')
    op.drop_table('change_sets')
    op.drop_index(op.f('ix_publications_planning_version_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_checksum_sha256'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_layers_thematic_group'), table_name='layers')
    op.drop_index(op.f('ix_layers_dataset_id'), table_name='layers')
    op.drop_index(op.f('ix_layers_canonical_name'), table_name='layers')
    op.drop_table('layers')
    op.drop_index(op.f('ix_georeference_jobs_review_status'), table_name='georeference_jobs')
    op.drop_table('georeference_jobs')
    op.drop_index(op.f('ix_documents_planning_version_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_normalized_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_number'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_datasets_review_status'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_planning_version_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_derivation_level'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_dataset_group'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_quality_target', table_name='quality_observations')
    op.drop_index('ix_quality_rule', table_name='quality_observations')
    op.drop_index('ix_quality_open', table_name='quality_observations')
    op.drop_table('quality_observations')
    op.drop_index('ix_provenance_target', table_name='provenance_events')
    op.drop_index('ix_provenance_run', table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_created_at'), table_name='provenance_events')
    op.drop_table('provenance_events')
    op.drop_index('ix_planning_versions_record_effective', table_name='planning_versions')
    op.drop_index(op.f('ix_planning_versions_planning_record_id'), table_name='planning_versions')
    op.drop_index(op.f('ix_planning_versions_effective_from'), table_name='planning_versions')
    op.drop_index(op.f('ix_planning_versions_approval_decision_number'), table_name='planning_versions')
    op.drop_table('planning_versions')
    op.drop_index('ix_source_artifacts_url', table_name='source_artifacts')
    op.drop_index('ix_source_artifacts_source_sha', table_name='source_artifacts')
    op.drop_index(op.f('ix_source_artifacts_content_sha256'), table_name='source_artifacts')
    op.drop_table('source_artifacts')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_sources_jurisdiction'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_planning_records_planning_type'), table_name='planning_records')
    op.drop_index(op.f('ix_planning_records_official_information_code'), table_name='planning_records')
    op.drop_index(op.f('ix_planning_records_official_file_code'), table_name='planning_records')
    op.drop_index(op.f('ix_planning_records_normalized_title'), table_name='planning_records')
    op.drop_index(op.f('ix_planning_records_jurisdiction'), table_name='planning_records')
    op.drop_table('planning_records')
    op.drop_index(op.f('ix_coverage_summaries_admin_unit_id'), table_name='coverage_summaries')
    op.drop_table('coverage_summaries')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_index('ix_review_target', table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_authorities_normalized_name'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_jurisdiction'), table_name='authorities')
    op.drop_table('authorities')
    op.drop_index('ix_admin_units_name', table_name='administrative_units')
    op.drop_index('ix_admin_units_code_valid', table_name='administrative_units')
    op.drop_table('administrative_units')
    # ### end Alembic commands ###
